### ISSUE TITLE
Can't install SPARK

### ISSUE THREAD

**Issue by cwu235** [xzhoulab/SPARK#1]
Hello,

When I tried to install SPARK by running the code on RStudio:

install.packages("remotes")
remotes::install_github("xzhoulab/SPARK")

It gives me an error code shown in the picture below
![image](https://user-images.githubusercontent.com/66337060/86652061-11169d00-bfb2-11ea-9961-82818a54aaf6.png)

Edit*:
Then I tried code:

install.packages('devtools')
devtools::install_github('xzhoulab/SPARK')

But got another error message:
![image](https://user-images.githubusercontent.com/66337060/86677750-e59fac80-bfc9-11ea-928d-d142d1c08dc1.png)

Edit**:
installed doSNOW and pbmcapply package
got an error message:
![image](https://user-images.githubusercontent.com/66337060/86681623-c014a200-bfcd-11ea-9768-71cb5747ab48.png)

**Comment by JulieBaker1** [comment]
try to install the package "Rcpp",if fail again,delete the existed "Rcpp"  and install again.

**Comment by giovp** [comment]
also same problem
```R
The downloaded binary packages are in
	/var/folders/3t/lc9m5zv966934dq4d6gf6l60g_dj6h/T//RtmpcMKukX/downloaded_packages
✓  checking for file ‘/private/var/folders/3t/lc9m5zv966934dq4d6gf6l60g_dj6h/T/RtmpcMKukX/remotes2a5c4513e8f5/xzhoulab-SPARK-2d62a4e/DESCRIPTION’ ...
─  preparing ‘SPARK’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  installing the package to process help pages
         -----------------------------------
─  installing *source* package ‘SPARK’ ...
   ** using staged installation
   ** libs
   clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I/usr/local/include    -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
   clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I/usr/local/include    -fPIC  -Wall -g -O2  -c rcpparma_hello_world.cpp -o rcpparma_hello_world.o
   clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I/usr/local/include    -fPIC  -Wall -g -O2  -c spark_float.cpp -o spark_float.o
   clang++ -mmacosx-version-min=10.13 -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o SPARK.so RcppExports.o rcpparma_hello_world.o spark_float.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
   ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
   ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
   ld: library not found for -lgfortran
   clang: error: linker command failed with exit code 1 (use -v to see invocation)
   make: *** [SPARK.so] Error 1
   ERROR: compilation failed for package ‘SPARK’
─  removing ‘/private/var/folders/3t/lc9m5zv966934dq4d6gf6l60g_dj6h/T/RtmpIb0USm/Rinst2ab42d5a60ab/SPARK’
```

**Comment by jakezhusph** [comment]
> ```r
> lgfortran
> ```

Hi Sorry for the late reply. It seems the gfortran is not well installed on your Mac. please check this [link](https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos/) for the gfortran installation. I solved the problem by following this tutorial on my Mac.

**Comment by jakezhusph** [comment]
> also same problem
> 
> ```r
> The downloaded binary packages are in
> 	/var/folders/3t/lc9m5zv966934dq4d6gf6l60g_dj6h/T//RtmpcMKukX/downloaded_packages
> ✓  checking for file ‘/private/var/folders/3t/lc9m5zv966934dq4d6gf6l60g_dj6h/T/RtmpcMKukX/remotes2a5c4513e8f5/xzhoulab-SPARK-2d62a4e/DESCRIPTION’ ...
> ─  preparing ‘SPARK’:
> ✓  checking DESCRIPTION meta-information ...
> ─  cleaning src
> ─  installing the package to process help pages
>          -----------------------------------
> ─  installing *source* package ‘SPARK’ ...
>    ** using staged installation
>    ** libs
>    clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I/usr/local/include    -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
>    clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I/usr/local/include    -fPIC  -Wall -g -O2  -c rcpparma_hello_world.cpp -o rcpparma_hello_world.o
>    clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I/usr/local/include    -fPIC  -Wall -g -O2  -c spark_float.cpp -o spark_float.o
>    clang++ -mmacosx-version-min=10.13 -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o SPARK.so RcppExports.o rcpparma_hello_world.o spark_float.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
>    ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
>    ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
>    ld: library not found for -lgfortran
>    clang: error: linker command failed with exit code 1 (use -v to see invocation)
>    make: *** [SPARK.so] Error 1
>    ERROR: compilation failed for package ‘SPARK’
> ─  removing ‘/private/var/folders/3t/lc9m5zv966934dq4d6gf6l60g_dj6h/T/RtmpIb0USm/Rinst2ab42d5a60ab/SPARK’
> ```

Hi Sorry for the late reply. It seems the gfortran is not well installed on your Mac. please check this [link](https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos/) for the gfortran installation. I solved the problem by following this tutorial on my Mac.

**Comment by jinyuanchun** [comment]
also same problem
tried to install SPARK by running the code on windows system:
use cmd:
     devtools::install_local("D:\\project\\SPARK")
my  rtools40 installed in C:\RBuildTools\4.0\mingw64\bin



   ERROR: compilation failed for package 'SPARK'
-  removing 'C:/Users/JINYUA~1/AppData/Local/Temp/RtmpAB8rfH/Rinst337c5b554578/SPARK'
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'SPARK' from local:
  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
E> * installing *source* package 'SPARK' ...
E> ** using staged installation
E> ** libs
E> "c:/rtools40/mingw64/bin/"g++  -std=gnu++11 -I"D:/Program/R/R-4.1.1/include" -DNDEBUG  -I'D:/Program/R/R-4.1.1/library/Rcpp/include' -I'D:/Program/R/R-4.1.1/library/RcppArmadillo/include'     -fopenmp -DARMA_64BIT_WORD=1   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -Wall -pedantic -c RcppExports.cpp -o RcppExports.o
E> sh: line 1: c:/rtools40/mingw64/bin/g++: No such file or directory
E> make: *** [D:/Program/R/R-4.1.1/etc/x64/Makeconf:245: RcppExports.o] Error 127
E> ERROR: compilation failed for package 'SPARK'
E> * removing 'C:/Users/JINYUA~1/AppData/Local/Temp/RtmpAB8rfH/Rinst337c5b554578/SPARK'
E>       -----------------------------------
E> ERROR: package installation failed

**Comment by jinyuanchun** [comment]
> also same problem tried to install SPARK by running the code on windows system: use cmd: devtools::install_local("D:\project\SPARK") my rtools40 installed in C:\RBuildTools\4.0\mingw64\bin
> 
> ERROR: compilation failed for package 'SPARK'
> 
> * removing 'C:/Users/JINYUA~1/AppData/Local/Temp/RtmpAB8rfH/Rinst337c5b554578/SPARK'
>   -----------------------------------
>   ERROR: package installation failed
>   Error: Failed to install 'SPARK' from local:
>   System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
>   E> * installing _source_ package 'SPARK' ...
>   E> ** using staged installation
>   E> ** libs
>   E> "c:/rtools40/mingw64/bin/"g++  -std=gnu++11 -I"D:/Program/R/R-4.1.1/include" -DNDEBUG  -I'D:/Program/R/R-4.1.1/library/Rcpp/include' -I'D:/Program/R/R-4.1.1/library/RcppArmadillo/include'     -fopenmp -DARMA_64BIT_WORD=1   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -Wall -pedantic -c RcppExports.cpp -o RcppExports.o
>   E> sh: line 1: c:/rtools40/mingw64/bin/g++: No such file or directory
>   E> make: *** [D:/Program/R/R-4.1.1/etc/x64/Makeconf:245: RcppExports.o] Error 127
>   E> ERROR: compilation failed for package 'SPARK'
>   E> * removing 'C:/Users/JINYUA~1/AppData/Local/Temp/RtmpAB8rfH/Rinst337c5b554578/SPARK'
>   E>       -----------------------------------
>   E> ERROR: package installation failed

thank u, my problem was solved
