### ISSUE TITLE
Error in spark.test

### ISSUE THREAD

**Issue by jasperhyp** [xzhoulab/SPARK#3]
I got an error message when trying to conduct the test:
```{R}
> spark <- spark.test(spark, check_positive = T, verbose = F)
## testing Gaussian kernel: 1...
Error in { : 
  task 1 failed - "arguments imply differing number of rows: 0, 1"
 ```
What does this mean?  I checked my original data and did not find any obvious peculiarities.

**Comment by jasperhyp** [comment]
It broke here on line 155 in `vctesting.R`:
```
res_each <- data.frame(geneid = names(object@res_vc)[ig], sw=davies_sw, converged=converged)
```
The first object `names(object@res_vc)[ig]` returns `NULL`, while the second returns something of length 1.

**Comment by jasperhyp** [comment]
Ok I guess I've found this bug...  I'm inputing a `base::matrix` as `count` variable to generate the SPARK object.
In this case, rownames of `count` does not persist.
However, that `rownames(counts)` was then used in the file `vcestimate.R` to name the `res_vc`:
```
names(res_vc) <- rownames(object@counts)
```
And then as my previous comment suggested, a `NULL` came out finally.  
Fixed.

**Comment by HelloWorldLTY** [comment]
Hi, I suffer from the same problem... So what you intend to say is choosing other format data as input? Which format can work? Thanks a lot.
