### ISSUE TITLE
Can't install SPARK on macOS 

### ISSUE THREAD

**Issue by wzw14541** [xzhoulab/SPARK#4]
These were the error information, I use R 4.10 on macOS:
> install.packages("~/Desktop/data/Spatial/SPARK-master", repos = NULL, type = "source")
Installing package into ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library’
(as ‘lib’ is unspecified)
* installing *source* package ‘SPARK’ ...
** using staged installation
** libs
make: Nothing to be done for `all'.
installing to /Library/Frameworks/R.framework/Versions/4.0/Resources/library/00LOCK-SPARK-master/00new/SPARK/libs
** R
** data
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘SPARK’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/00LOCK-SPARK-master/00new/SPARK/libs/SPARK.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/00LOCK-SPARK-master/00new/SPARK/libs/SPARK.so, 6): no suitable image found.  Did find:
	/Library/Frameworks/R.framework/Versions/4.0/Resources/library/00LOCK-SPARK-master/00new/SPARK/libs/SPARK.so: unknown file type, first eight bytes: 0x23 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01
	/Library/Frameworks/R.framework/Versions/4.0/Resources/library/00LOCK-SPARK-master/00new/SPARK/libs/SPARK.so: unknown file type, first eight bytes: 0x23 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/SPARK’
Warning in install.packages :
  installation of package ‘/Users/wangziwei/Desktop/data/时空组学/SPARK-master’ had non-zero exit status

**Comment by jakezhusph** [comment]
have you solved the problem? I was able to install the package on R 4.2.0 on a Mac notebook. Let me know if you encounter any other problems.
