### ISSUE TITLE
Cannot install package

### ISSUE THREAD

**Issue by nganphtgit** [xzhoulab/SPARK#6]
OS: MacOS Monterey
Chip: M1
R version: 4.1.2
Details:
```
installing *source* package ‘SPARK’ ...
   ** using staged installation
   ** libs
   clang++ -arch arm64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/RcppArmadillo/include' -I/opt/R/arm64/include   -DARMA_64BIT_WORD=1 -fPIC  -falign-functions=64 -Wall -g -O2  -Wall -pedantic -fdiagnostics-color=always -c RcppExports.cpp -o RcppExports.o
   clang++ -arch arm64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/RcppArmadillo/include' -I/opt/R/arm64/include   -DARMA_64BIT_WORD=1 -fPIC  -falign-functions=64 -Wall -g -O2  -Wall -pedantic -fdiagnostics-color=always -c rcpparma_hello_world.cpp -o rcpparma_hello_world.o
   clang++ -arch arm64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/RcppArmadillo/include' -I/opt/R/arm64/include   -DARMA_64BIT_WORD=1 -fPIC  -falign-functions=64 -Wall -g -O2  -Wall -pedantic -fdiagnostics-color=always -c spark_float.cpp -o spark_float.o
clang++ -arch arm64 -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/opt/R/arm64/lib -o SPARK.so RcppExports.o rcpparma_hello_world.o spark_float.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/   clang++ -arch arm64 -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/opt/R/arm64/lib -o SPARK.so RcppExports.o rcpparma_hello_world.o spark_float.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/opt/R/arm64/gfortran/lib/gcc/aarch64-apple-darwin20.2.0/11.0.0 -L/opt/R/arm64/gfortran/lib -lgfortran -lemutls_w -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
   ld: warning: directory not found for option '-L/opt/R/arm64/gfortran/lib/gcc/aarch64-apple-darwin20.2.0/11.0.0'
   ld: warning: directory not found for option '-L/opt/R/arm64/gfortran/lib'
   ld: library not found for -lgfortran
   clang: error: linker command failed with exit code 1 (use -v to see invocation)
   make: *** [SPARK.so] Error 1
   ERROR: compilation failed for package ‘SPARK’
─  removing ‘/private/var/folders/lx/m9g2zys973n5n64srkk6njlh0000gn/T/RtmpxjAxzJ/Rinst9cfc53d1611c/SPARK’
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'SPARK' from GitHub:
  System command 'R' failed, exit status: 1, stdout & stderr were printed
```

**Comment by yangfeizZZ** [comment]
> Sorry for the late reply. Have you solved the problem? Recently, I was able to install the package on a M1Pro Mac. Let me know if you have problems with the package after reinstall the gfortran on your Mac.
On the win11,i also can not install this pachake

**Comment by jakezhusph** [comment]
> Sorry for the late reply. Have you solved the problem? Recently, I was able to install the package on a M1Pro Mac. Let me know if you have problems with the package after reinstall the gfortran on your Mac.
> On the win11,i also can not install this pachake

Would you please share the error info?

**Comment by yangfeizZZ** [comment]
I solve it,thank u.But i have anothor problem.how can look the SV which was find by spark?













At 2022-06-23 10:27:23, "jiaqiang zhu" ***@***.***> wrote:

Sorry for the late reply. Have you solved the problem? Recently, I was able to install the package on a M1Pro Mac. Let me know if you have problems with the package after reinstall the gfortran on your Mac.
On the win11,i also can not install this pachake

Would you please share the error info?

**Comment by jakezhusph** [comment]
> I solve it,thank u.But i have anothor problem.how can look the SV which was find by spark? At 2022-06-23 10:27:23, "jiaqiang zhu" ***@***.***> wrote: Sorry for the late reply. Have you solved the problem? Recently, I was able to install the package on a M1Pro Mac. Let me know if you have problems with the package after reinstall the gfortran on your Mac. On the win11,i also can not install this pachake Would you please share the error info? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

Please check this website for the analysis procedures with SPARK: https://xzhoulab.github.io/SPARK/.

**Comment by yangfeizZZ** [comment]
Thank you.I get it.










At 2022-06-23 21:35:21, "jiaqiang zhu" ***@***.***> wrote:

I solve it,thank u.But i have anothor problem.how can look the SV which was find by spark? At 2022-06-23 10:27:23, "jiaqiang zhu" @.> wrote: Sorry for the late reply. Have you solved the problem? Recently, I was able to install the package on a M1Pro Mac. Let me know if you have problems with the package after reinstall the gfortran on your Mac. On the win11,i also can not install this pachake Would you please share the error info? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.>

Please check this website for the analysis procedures with SPARK: https://xzhoulab.github.io/SPARK/.
